progress in getting the libraries we want in the build

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -44,12 +44,14 @@ else
   MJOBS=4
 fi
 
-make_dir() {
-  remove_dir "$1"
-  if ! mkdir "$1"; then
-    printf "\n Failed to create dir %s" "$1"
-    exit 1
-  fi
+CONFIGURE_OPTIONS+=("--extra-version=beamcube")
+
+make_dir () {
+	remove_dir "$1"
+	if ! mkdir "$1"; then
+		printf "\n Failed to create dir %s" "$1"
+		exit 1
+	fi
 }
 
 remove_dir() {
@@ -358,6 +360,11 @@ if build "autoconf" "2.71"; then
   build_done "autoconf" "2.71"
 fi
 
+if build "meson"; then
+  execute python3 -m pip install meson ninja
+  build_done "meson"
+fi
+
 if build "automake" "1.16.4"; then
   download "https://ftp.gnu.org/gnu/automake/automake-1.16.4.tar.gz"
   execute ./configure --prefix="${WORKSPACE}"
@@ -492,6 +499,7 @@ fi
     mv libx265.a libx265_main.a
 
     if [[ "$OSTYPE" == "darwin"* ]]; then
+      execute install_name_tool -id "${WORKSPACE}/lib/libx265.198.dylib" libx265.198.dylib
       execute "${MACOS_LIBTOOL}" -static -o libx265.a libx265_main.a libx265_main10.a libx265_main12.a 2>/dev/null
     else
       execute ar -M <<EOF
@@ -528,7 +536,7 @@ if build "libvpx" "1.10.0"; then
   execute make -j $MJOBS
 
   if [[ "$OSTYPE" == "darwin"* ]]; then
-	  install_name_tool -id "${WORKSPACE}/lib/libvpx.6.dylib" libvpx.6.dylib
+	  execute install_name_tool -id "${WORKSPACE}/lib/libvpx.6.dylib" libvpx.6.dylib
 	fi
 
   execute make install
@@ -569,12 +577,27 @@ CONFIGURE_OPTIONS+=("--enable-libvpx")
 
     execute cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DUSE_OMP=OFF -DENABLE_SHARED=on .
     execute make
+
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+	    execute install_name_tool -id "${WORKSPACE}/lib/libvidstab.1.1.dylib" libvidstab.1.1.dylib
+	  fi
+
     execute make install
 
     build_done "vid_stab" "1.1.0"
   fi
   CONFIGURE_OPTIONS+=("--enable-libvidstab")
 # fi
+
+if build "twolame"; then
+  download "https://downloads.sourceforge.net/twolame/twolame-0.4.0.tar.gz"
+  execute ./configure --prefix="${WORKSPACE}" --enable-shared --disable-static
+	execute make -j $MJOBS
+	execute make install
+
+	build_done "twolame"
+fi
+CONFIGURE_OPTIONS+=("--enable-libtwolame")
 
 if build "av1" "ae2be80"; then
   # libaom ae2be80 == v3.1.2
@@ -587,6 +610,9 @@ if build "av1" "ae2be80"; then
     execute cmake -DEBUILD_SHARED_LIBS=1 -DENABLE_TESTS=0 -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_LIBDIR=lib "$PACKAGES"/av1
   fi
   execute make -j $MJOBS
+  if [[ "$OSTYPE" == "darwin"* ]]; then
+	  execute install_name_tool -id "${WORKSPACE}/lib/libaom.2.dylib" libaom.2.dylib
+	fi
   execute make install
 
   build_done "av1" "ae2be80"
@@ -604,6 +630,17 @@ if build "zimg" "3.0.3"; then
   build_done "zimg" "3.0.3"
 fi
 CONFIGURE_OPTIONS+=("--enable-libzimg")
+
+# get prebuilt binaries
+if build "openh264"; then
+  download "https://github.com/cisco/openh264/archive/v2.1.1.tar.gz" "openh264-2.1.1.tar.gz"
+  execute export PREFIX="${WORKSPACE}"
+  execute make
+  execute make install-shared
+
+	build_done "openh264"
+fi
+CONFIGURE_OPTIONS+=("--enable-libopenh264")
 
 ##
 ## audio library
@@ -713,7 +750,7 @@ fi
 
 if build "libvorbis" "1.3.6"; then
   download "https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.6.tar.gz"
-  execute ./configure --prefix="${WORKSPACE}" --with-ogg-libraries="${WORKSPACE}"/lib --with-ogg-includes="${WORKSPACE}"/include/ --disable-static --enable-shared --disable-oggtest
+  OGG_CFLAGS="-I${WORKSPACE}/include/ogg" OGG_LIBS="-L${WORKSPACE}/lib -logg" execute ./configure --prefix="${WORKSPACE}" --with-ogg-libraries="${WORKSPACE}"/lib --with-ogg-includes="${WORKSPACE}"/include/ --disable-static --enable-shared --disable-oggtest
   execute make -j $MJOBS
   execute make install
 
@@ -726,13 +763,46 @@ if build "libtheora" "1.1.1"; then
   sed "s/-fforce-addr//g" configure >configure.patched
   chmod +x configure.patched
   mv configure.patched configure
-  execute ./configure --prefix="${WORKSPACE}" --with-ogg-libraries="${WORKSPACE}"/lib --with-ogg-includes="${WORKSPACE}"/include/ --with-vorbis-libraries="${WORKSPACE}"/lib --with-vorbis-includes="${WORKSPACE}"/include/ --disable-static --enable-shared --disable-oggtest --disable-vorbistest --disable-examples --disable-asm --disable-spec
+  OGG_CFLAGS="-I${WORKSPACE}/include/ogg" OGG_LIBS="-L${WORKSPACE}/lib -logg" execute ./configure --prefix="${WORKSPACE}" --with-ogg-libraries="${WORKSPACE}"/lib --with-ogg-includes="${WORKSPACE}"/include/ --with-vorbis-libraries="${WORKSPACE}"/lib --with-vorbis-includes="${WORKSPACE}"/include/ --disable-static --enable-shared --disable-oggtest --disable-vorbistest --disable-examples --disable-asm --disable-spec
   execute make -j $MJOBS
   execute make install
 
   build_done "libtheora" "1.1.1"
 fi
 CONFIGURE_OPTIONS+=("--enable-libtheora")
+
+if build "shine"; then
+  download "https://github.com/toots/shine/archive/3.1.1.tar.gz" "shine-3.1.1.tar.gz"
+  execute autoreconf -i
+  execute ./configure --prefix="${WORKSPACE}" --enable-shared --disable-static
+  execute make -j $MJOBS
+  execute make install
+
+  build_done "shine"
+fi
+CONFIGURE_OPTIONS+=("--enable-libshine")
+
+if build "soxr"; then
+  download "http://ftp.debian.org/debian/pool/main/libs/libsoxr/libsoxr_0.1.3.orig.tar.xz" "soxr-0.1.3.tar.xz"
+  make_dir build
+  cd build || exit
+  execute cmake .. -DWITH_OPENMP:BOOL=OFF -Wno-dev -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON
+  execute make -j $MJOBS
+	execute make install
+
+  build_done "soxr"
+fi
+CONFIGURE_OPTIONS+=("--enable-libsoxr")
+
+if build "speex"; then
+  download "http://downloads.us.xiph.org/releases/speex/speex-1.2.0.tar.gz"
+  execute ./configure --prefix="${WORKSPACE}" --enable-shared --disable-static
+  execute make -j $MJOBS
+  execute make install
+
+  build_done "speex"
+fi
+CONFIGURE_OPTIONS+=("--enable-libspeex")
 
 ##
 ## image library
@@ -770,6 +840,19 @@ if build "libwebp" "1.2.0"; then
 fi
 CONFIGURE_OPTIONS+=("--enable-libwebp")
 
+if build "openjpeg"; then
+  download "https://github.com/uclouvain/openjpeg/archive/v2.3.1.tar.gz" "openjpeg-v2.3.1.tar.gz"
+	make_dir build
+	cd build || exit
+	execute cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DBUILD_SHARED_LIBS:bool=on
+	execute make -j $MJOBS
+	execute make install
+
+	build_done "openjpeg"
+fi
+CONFIGURE_OPTIONS+=("--enable-libopenjpeg")
+
+
 ##
 ## other library
 ##
@@ -783,21 +866,40 @@ if build "libsdl" "2.0.14"; then
   build_done "libsdl" "2.0.14"
 fi
 
-#if build "srt"; then
-#	download "https://github.com/Haivision/srt/archive/v1.4.1.tar.gz" "srt-1.4.1.tar.gz"
-#	export OPENSSL_ROOT_DIR="${WORKSPACE}"
-#	export OPENSSL_LIB_DIR="${WORKSPACE}"/lib
-#	export OPENSSL_INCLUDE_DIR="${WORKSPACE}"/include/
-#	execute cmake . -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_BINDIR=bin -DCMAKE_INSTALL_INCLUDEDIR=include -DENABLE_SHARED=ON -DENABLE_STATIC=OFF -DENABLE_APPS=OFF -DUSE_STATIC_LIBSTDCXX=ON
+if build "snappy"; then
+  download "https://github.com/google/snappy/archive/1.1.8.tar.gz"
+  make_dir build
+  cd build || exit
+  execute cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DBUILD_SHARED_LIBS:bool=on
+  execute make -j $MJOBS
+
+  if [[ "$OSTYPE" == "darwin"* ]]; then
+	  execute install_name_tool -id "${WORKSPACE}/lib/libsnappy.1.dylib" libsnappy.1.dylib
+	fi
+
+  execute make install
+
+  build_done "snappy"
+fi
+CONFIGURE_OPTIONS+=("--enable-libsnappy")
+
+if build "xz"; then
+  download "https://tukaani.org/xz/xz-5.2.5.tar.gz"
+	execute ./configure --prefix="${WORKSPACE}" --enable-shared --disable-static
+	execute make -j $MJOBS
+	execute make install
+
+	build_done "xz"
+fi
+
+#if build "libass"; then
+#  download "https://github.com/libass/libass/releases/download/0.15.0/libass-0.15.0.tar.gz"
+#  execute ./configure --prefix="${WORKSPACE}" --enable-shared --disable-static
+#  execute make -j $MJOBS
 #	execute make install
 #
-#	if [ -n "$LDEXEFLAGS" ]; then
-#		sed -i.backup 's/-lgcc_s/-lgcc_eh/g' "${WORKSPACE}"/lib/pkgconfig/srt.pc # The -i.backup is intended and required on MacOS: https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux
-#	fi
-#
-#	build_done "srt"
+#  build_done "libass"
 #fi
-#CONFIGURE_OPTIONS+=("--enable-libsrt")
 
 
 ##
@@ -919,6 +1021,11 @@ elif [[ ! "$SKIPINSTALL" == "yes" ]]; then
     echo "Done. FFmpeg is now installed to your system."
     ;;
   esac
+fi
+
+cd $CWD
+if [[ "$OSTYPE" == "darwin"* ]]; then
+  node copy_mac_libs.js
 fi
 
 exit 0
