Add GPL-only option and includes some libraries
beamcoder needs libpostproc

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -18,6 +18,7 @@ CONFIGURE_OPTIONS=()
 NONFREE_AND_GPL=false
 LATEST=false
 SHARED_LIBRARIES=false
+FREE_AND_GPL=false
 
 # Check for Apple Silicon
 if [[ ("$(uname -m)" == "arm64") && ("$OSTYPE" == "darwin"*) ]]; then
@@ -205,6 +206,7 @@ usage() {
   echo "      --full-static              Build a full static FFmpeg binary (eg. glibc, pthreads etc...) **only Linux**"
   echo "                                 Note: Because of the NSS (Name Service Switch), glibc does not recommend static links."
   echo "      --full-shared              Build all shared libraries. Cannot be used with --full-static"
+  echo "      --enable-gpl-and-free      Enable GPL but not non-free codecs. Cannot be used with --enable-gpl-and-non-free - https://ffmpeg.org/legal.html"
   echo ""
 }
 
@@ -248,6 +250,10 @@ while (($# > 0)); do
     if [[ "$1" == "--full-shared" ]]; then
       SHARED_LIBRARIES=true
     fi
+    if [[ "$1" == "--enable-gpl-and-free" ]]; then
+      CONFIGURE_OPTIONS+=("--enable-gpl")
+      FREE_AND_GPL=true
+    fi
     shift
     ;;
   *)
@@ -270,6 +276,11 @@ if [[ ($SHARED_LIBRARIES == true) && ($LDEXEFLAGS == true) ]]; then
   exit 1
 fi
 
+if [[ ($NONFREE_AND_GPL == true) && ($FREE_AND_GPL == true) ]]; then
+  usage
+  exit 1
+fi
+
 echo "Using $MJOBS make jobs simultaneously."
 
 if $NONFREE_AND_GPL; then
@@ -282,6 +293,10 @@ fi
 
 if $SHARED_LIBRARIES; then
   echo "Building shared libraries."
+fi
+
+if $FREE_AND_GPL; then
+  echo "GPL and free codecs"
 fi
 
 mkdir -p "$PACKAGES"
@@ -491,7 +506,7 @@ if command_exists "cargo"; then
   CONFIGURE_OPTIONS+=("--enable-librav1e")
 fi
 
-if $NONFREE_AND_GPL; then
+if $NONFREE_AND_GPL || $FREE_AND_GPL; then
 
   if build "x264" "5db6aa6"; then
     download "https://code.videolan.org/videolan/x264/-/archive/5db6aa6cab1b146e07b60cc1736a01f21da01154/x264-5db6aa6cab1b146e07b60cc1736a01f21da01154.tar.gz" "x264-5db6aa6.tar.gz"
@@ -524,7 +539,7 @@ if $NONFREE_AND_GPL; then
   CONFIGURE_OPTIONS+=("--enable-libx264")
 fi
 
-if $NONFREE_AND_GPL; then
+if $NONFREE_AND_GPL || $FREE_AND_GPL; then
   if build "x265" "3.5"; then
     download "https://github.com/videolan/x265/archive/Release_3.5.tar.gz" "x265-3.5.tar.gz" # This is actually 3.4 if looking at x265Version.txt
     cd build/linux || exit
@@ -606,7 +621,7 @@ if false; then
   CONFIGURE_OPTIONS+=("--enable-libvpx")
 fi
 
-if $NONFREE_AND_GPL; then
+if $NONFREE_AND_GPL || $FREE_AND_GPL; then
   if build "xvidcore" "1.3.7"; then
     download "https://downloads.xvid.com/downloads/xvidcore-1.3.7.tar.gz"
     cd build/generic || exit
